FCBHDBP-579 bibleis-web: invalid CDN request
faithcomesbyhearing/dbp-web pull request #72
Opened 2023-06-29 20:05 UTC by vichugofsl

# Description
The issue causing an infinite loop when a video chunk failed has been resolved. The fix involved eliminating a poor practice of retrying a failed request. Additionally, I've mitigated around 70 vulnerabilities by overriding three packages and removing some that are no longer necessary. Finally, I have overwritten the Load Policies: `playlistLoadPolicy`, `fragLoadPolicy` and `keyLoadPolicy` to use the exponential strategy for the backoff parameter.

However, I am still encountering some CORS errors for specific videos, such as /bible/FRAPDF/MAT/1.

## Related Issue

https://fullstacklabs.atlassian.net/browse/FCBHDBP-580

## How to Test
- You should go the path: `bible/EN1ESV/MAT/1` and it must load the correct page and the console doesn't render errors.
- You should go the path: `bible/FRAPDF/MAT/1` and it must load the correct page and the console doesn't render errors.

2023-06-29 21:23 UTC, bradflood requested changes

2023-06-29 21:23 UTC, bradflood commented on app/containers/VideoPlayer/index.js
> +            maxNumRetry: 2,
I think we should retry at least four times for all situations; two is not enough.

2023-06-29 22:20 UTC, vichugofsl commented on app/containers/VideoPlayer/index.js
> +            maxNumRetry: 2,
@bradflood , I have updated it and all situations will have maxNumRetry value greater or equal than 4.

2023-06-29 22:44 UTC, bradflood commented on app/containers/VideoPlayer/index.js
> +            retryDelayMs: 0,
now the delay and maxDelay look wrong. how about retryDelayMs 1000 and maxRetryDelayMs 20000. Or are these specific to timeout retries, in which the delay has already been baked in?

2023-06-30 00:13 UTC, vichugofsl commented on app/containers/VideoPlayer/index.js
> +            retryDelayMs: 0,
@bradflood I have updated the parameters 'retryDelayMs' and 'maxRetryDelayMs' to 1000 and 20000 respectively, based on the documentation. This adjustment ensures that the system retries with the specified delay time after encountering a timeout error.

2023-06-30 01:30 UTC, bradflood approved these changes

2023-06-30 13:45 UTC, merged